<?php if (Mage::helper('space48_trackingcodes')->getCriteoIsEnabled()): ?>
    <script type="text/javascript" src="//static.criteo.net/js/ld/ld.js" async="true"></script>
    <script type="text/javascript">
        window.criteo_q = window.criteo_q || [];
        window.criteo_q.push(
            { event: "setAccount", account: <?php echo Mage::helper('space48_trackingcodes')->getCriteoClientId() ?>},
            { event: "setSiteType", type: "d" },
            { event: "setEmail", email: "<?php echo Mage::helper('space48_trackingcodes')->getCriteoEmail() ?>" },
            { event: "viewBasket", item: [<?php echo Mage::getModel('space48_trackingcodes/criteo')->getBasketParams() ?>]});
    </script>
<?php endif; ?>
