<?php if (Mage::helper('space48_trackingcodes')->getCriteoIsEnabled()): ?>
    <script type="text/javascript" src="//static.criteo.net/js/ld/ld.js" async="true"></script>
    <script type="text/javascript">
        window.criteo_q = window.criteo_q || [];
        window.criteo_q.push(
            { event: "setAccount", account: <?php echo Mage::helper('space48_trackingcodes')->getCriteoClientId() ?>},
            { event: "setEmail", email: customer_email },
            { event: "setSiteType", type: "d" },
            { event: "viewHome" }
        );
    </script>
<?php endif; ?>