<script type="text/javascript" src="//static.criteo.net/js/ld/ld.js" async="true"></script>
<script type="text/javascript">
    window.criteo_q = window.criteo_q || [];
    window.criteo_q.push(
        { event: "setAccount", account: <?php echo $this->getAccountId() ?>},
        { event: "setSiteType", type: "d" },
        { event: "setEmail", email: "<?php echo $this->getEmail() ?>" },
        { event: "trackTransaction" , id: "<?php $this->getLastOrderId() ?>",
            item: [<?php echo $this->getConfirmationParams() ?>]});
</script>