<?php if ($this->getCanShow()): ?>

<script id="reevoomark-loader" type="text/javascript" charset="utf-8">
    (function() {
        var trkref = '<?php echo $this->getTrackingReference(); ?>';
        var myscript = document.createElement('script');
        myscript.type = 'text/javascript';
        myscript.src=('//mark.reevoo.com/reevoomark/'+trkref+'.js?async=true');
        var s = document.getElementById('reevoomark-loader');
        s.parentNode.insertBefore(myscript, s);
    })();

    afterReevooMarkLoaded = [function(){
        ReevooMark.track_purchase([<?php echo $this->getItemSkus() ?>], <?php echo $this->getOrderTotal(); ?>);
    }];
</script>

<?php endif; ?>