<script type="text/javascript">
var aobmp=aobmp||[];aobmp.push(['init','<?php echo $this->getApiKey() ?>']);(function(){
var a=document.createElement("script");a.type="text/javascript";a.async=!0;
a.src=("https:"==document.location.protocol?"https://":"http://")+
"peermapcontent.affino.com/AfoCustom/Peermap/Log/aobmp3_m.js";
var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)})();
</script>