<?php $_helper = Mage::helper('space48_trackingcodes'); ?>
<?php $_model = Mage::getModel('space48_trackingcodes/remarketing'); ?>

<?php if ($_helper->getRemarketingConfig('enabled')): ?>
    <?php $cart_params = $_model->getBasketParams(); ?>
    <div style="display: none;">
        <script type="text/javascript">
            /* <![CDATA[ */
            var google_tag_params = {
                ecomm_prodid: '',
                ecomm_pagetype: 'basket',
                ecomm_totalvalue: '<?php echo $cart_params['cart_total'] ;?>'
            };

            var google_conversion_id = <?php echo $_helper->getRemarketingConfig('accountid'); ?>;
            var google_custom_params = window.google_tag_params;
            var google_remarketing_only = true;
            /* ]]> */
        </script>
        <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>
        <noscript>
            <div style="display:inline;">
                <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/<?php echo $_helper->getRemarketingConfig('accountid'); ?>/?value=0&amp;guid=ON&amp;script=0"/>
            </div>
        </noscript>
    </div>
<?php endif; ?>
