<div style="display: none;">
    <script type="text/javascript">
        /* <![CDATA[ */
        var google_tag_params = {
            ecomm_prodid: '<?php echo $this->getProductId() ?>',
            ecomm_pagetype: '<?php echo $this->getPageType() ?>',
            ecomm_totalvalue: '<?php echo $this->getTotalValue() ?>'
        };
        var google_conversion_id = <?php echo $this->getAccountId() ?>;
        var google_custom_params = window.google_tag_params;
        var google_remarketing_only = true;
        /* ]]> */
    </script>
    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>
    <noscript>
        <div style="display:inline;">
            <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/<?php echo $this->getAccountId(); ?>/?value=0&amp;guid=ON&amp;script=0"/>
        </div>
    </noscript>
</div>
